package com.aarvitex.webapp;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;

/**
 * HelloServlet — demonstrates a basic Java Servlet.
 *
 * Teaching Points (Maven → Jenkins Session):
 *  - This is a compiled Java class, NOT a JSP.
 *  - Maven compiles it to target/classes/com/aarvitex/webapp/HelloServlet.class
 *  - It gets bundled into the WAR under WEB-INF/classes/
 *  - Mapped in web.xml to the /hello URL
 *
 * Used in: Session 1 (Maven), Session 3 (Jenkins)
 */
public class HelloServlet extends HttpServlet {

    private static final String APP_NAME    = "Aarvitex WebApp";
    private static final String APP_VERSION = "1.0-SNAPSHOT";
    private static final String TRAINING    = "aarvitex.com";

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html;charset=UTF-8");

        String studentName = request.getParameter("name");
        if (studentName == null || studentName.trim().isEmpty()) {
            studentName = "DevOps Student";
        }

        PrintWriter out = response.getWriter();

        out.println("<!DOCTYPE html>");
        out.println("<html lang='en'>");
        out.println("<head>");
        out.println("  <meta charset='UTF-8'/>");
        out.println("  <meta name='viewport' content='width=device-width, initial-scale=1.0'/>");
        out.println("  <title>Hello — Aarvitex WebApp</title>");
        out.println("  <style>");
        out.println("    body { font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #e6edf3; min-height: 100vh; display: flex; align-items: center; justify-content: center; }");
        out.println("    .card { background: #161b22; border: 1px solid #21262d; border-radius: 16px; padding: 50px 60px; text-align: center; max-width: 520px; }");
        out.println("    .icon { font-size: 56px; margin-bottom: 20px; }");
        out.println("    h1 { font-size: 36px; color: #21a179; margin-bottom: 12px; }");
        out.println("    .sub { color: #8b949e; font-size: 15px; line-height: 1.6; margin-bottom: 28px; }");
        out.println("    .info-row { display: flex; justify-content: space-between; padding: 10px 0; border-top: 1px solid #21262d; font-size: 13px; }");
        out.println("    .info-key { color: #8b949e; font-family: monospace; }");
        out.println("    .info-val { color: #58a6ff; font-family: monospace; }");
        out.println("    .back { display: inline-block; margin-top: 28px; padding: 10px 24px; background: #21a17922; color: #21a179; border: 1px solid #21a179; border-radius: 8px; text-decoration: none; font-size: 14px; }");
        out.println("    .logo { font-size: 12px; color: #30363d; margin-top: 28px; letter-spacing: 2px; text-transform: uppercase; }");
        out.println("  </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("  <div class='card'>");
        out.println("    <div class='icon'>👋</div>");
        out.println("    <h1>Hello, " + escapeHtml(studentName) + "!</h1>");
        out.println("    <p class='sub'>This response was generated by a <strong>Java Servlet</strong> — compiled by Maven and deployed inside the AarvitexWebApp.war.</p>");
        out.println("    <div class='info-row'><span class='info-key'>App</span><span class='info-val'>" + APP_NAME + "</span></div>");
        out.println("    <div class='info-row'><span class='info-key'>Version</span><span class='info-val'>" + APP_VERSION + "</span></div>");
        out.println("    <div class='info-row'><span class='info-key'>Servlet Class</span><span class='info-val'>com.aarvitex.webapp.HelloServlet</span></div>");
        out.println("    <div class='info-row'><span class='info-key'>Java</span><span class='info-val'>" + System.getProperty("java.version") + "</span></div>");
        out.println("    <div class='info-row'><span class='info-key'>Server Time</span><span class='info-val'>" + new Date() + "</span></div>");
        out.println("    <a href='index.jsp' class='back'>← Back to Home</a>");
        out.println("    <div class='logo'>aarvitex.com · devops training</div>");
        out.println("  </div>");
        out.println("</body></html>");
    }

    /**
     * Basic HTML escaping to prevent XSS — good teaching point for SonarQube session.
     * SonarQube will flag any place where user input is written to output without escaping.
     */
    private String escapeHtml(String input) {
        if (input == null) return "";
        return input.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                    .replace("\"", "&quot;")
                    .replace("'", "&#x27;");
    }
}
